---
title: "Survival Analysis HW 1"
author: "Mario Ibanez"
date: "January 18, 2016"
output: pdf_document
---

# Problem 2.5
A model for lifetimes, with a bathtub-shaped hazard rate, is the exponential power distribution with survival function $S(x)=exp(1-exp((\lambda x)^\alpha))$.  
a) If $\alpha = 0.5$, show that the hazard rate has a bathtub shape and find the time at which the hazard rate changes from decreasing to increasing.  
b) If $\alpha = 2$, show that the hazard rate of $x$ is monotone increasing.

## Answer
First we find the hazard function:

\begin{align*}
h(x)
&= \frac{-S'(x)}{S(x)} \\[1ex]
&= \frac{exp(1-exp((\lambda x)^\alpha)) * e^{(\lambda x)^{\alpha}} \lambda ^ \alpha \alpha x^{\alpha - 1}}{exp(1-exp((\lambda x)^\alpha))} \\[1ex]
&= \alpha \lambda^{\alpha} x^{\alpha - 1} e^{(\lambda x)^{\alpha}}
\end{align*}

and 

\begin{align*}
h'(x)
&= \alpha \lambda^{\alpha} \left[(\alpha - 1)x^{\alpha - 2} exp((\lambda x)^{\alpha}) +
   x^{\alpha-1} exp((\lambda x)^{\alpha}) \alpha (\lambda x)^{\alpha - 1} \lambda  \right] \\[1ex]
&= \alpha \lambda^{\alpha} exp((\lambda x)^{\alpha}) \left[(\alpha - 1)x^{\alpha - 2}
   + x^{\alpha-1} \alpha (\lambda x)^{\alpha - 1} \lambda   \right]
\end{align*}

It's worth noting that in this distribution, $\lambda>0$ is the scale parameter, $\alpha>0$ is the shape parameter, and the support is $x>0$.

**a)** Let $\alpha = 0.5$.  Then:

\begin{align*}
h'(x)
&= \frac{1}{2} \sqrt{\lambda} e^{\sqrt{\lambda x}} \left[ \frac{-1}{2} x^{-3/2} + x^{-1/2}\frac{1}{2} (\lambda x)^{-1/2} \lambda \right] \\[1ex]
&= \frac{e^{\sqrt{\lambda x}} \sqrt{\lambda}} {2} \left[ \frac{\lambda}{2 \sqrt{x} \sqrt{\lambda} \sqrt{x}}  - \frac{1}{2 x \sqrt{x} }   \right] \\[1ex]
&= \frac{e^{\sqrt{\lambda x}} \sqrt{\lambda}} {2} \left[ \frac{\sqrt{\lambda}}{2x}  - \frac{1}{2x\sqrt{x}}   \right] \\[1ex]
&= \frac{e^{\sqrt{\lambda x}} \sqrt{\lambda}} {2} \left[ \frac{\sqrt{\lambda x} - 1}{2 x \sqrt{x}}  \right] 
\end{align*}

This is the product of two terms.  The term
$$
\frac{e^{\sqrt{\lambda x}} \sqrt{\lambda}} {2}
$$
is always positive.  The other term
$$
\frac{\sqrt{\lambda x} - 1}{2 x \sqrt{x}}  
$$
is zero when $x=\frac{1}{\lambda}$, is negative when $x<\frac{1}{\lambda}$ and is positive when $x>\frac{1}{\lambda}$.  (The denominator is always positive, only the numerator affects the sign of this term)  This shows that the hazard rate function has a bathtub shape and changes from decreasing to increasing at $x=\frac{1}{\lambda}$.   

**b)** Let $\alpha = 2$.  Then:

\begin{align*}
h'(x)
&= 2 \lambda^2 e^{(\lambda x)^2} \left[ 1 + x(2)(\lambda x) \lambda  \right]
\end{align*}

Since $x>0$ and $\lambda > 0$, it is easy to see that the derivative is always positive since the only operations are addition and multiplication of postive terms.  Thus, the hazard rate of $x$ is monotone increasing.

# Problem 2.8
The battery life of an internal pacemaker, in years, follows a Pareto distribution with $\theta = 4$ and $\lambda = 5$.   
a) What is the probability the battery will survive for at least 10 years?   
b) What is the mean time to battery failure?  
c) If the battery is scheduled to be replaced at the time $t_0$, at which 99% of all batteries have yet to fail (that is, at $t_0$ so that $P(X>t_0)=0.99$), find $t_0$.   

## Answer
The pdf of the Pareto distribution is 
$$
f(x) = 
\begin{cases} 
\frac{\theta \lambda^{\theta}}{x^{\theta+1}}   &\mbox{for } x \ge \lambda \\ 
0                                              &\mbox{otherwise }  
\end{cases}
$$
and with $\theta = 4$ and $\lambda = 5$
$$
f(x) = 
\begin{cases} 
\frac{2500}{x^5}   &\mbox{for } x \ge 5 \\ 
0                  &\mbox{otherwise }  
\end{cases}
$$

**a)** The probability that the battery will last for at least 10 years is
\begin{align*}
P(X \ge 10)
&= \int_{10}^{\infty} \frac{2500}{x^5} dx \\[1ex]
&= \left[ \frac{-625}{x^4}\right]^{\infty}_{10} \\[1ex]
&= 0+\frac{625}{10000} \\[1ex]
&= 0.0625 \\[1ex]
&= 6.25\%
\end{align*}
There is a 6.25% chance that the battery lasts longer than 10 years.   

**b)** The mean time to battery failure is
\begin{align*}
E(X)
&= \int_{5}^{\infty} x \frac{2500}{x^5} dx \\[1ex]
&= \int_{5}^{\infty} \frac{2500}{x^4} dx \\[1ex]
&= \left[ \frac{2500}{(-3)x^3}\right]^{\infty}_{5} \\[1ex]
&= 0 + \frac{2500}{(3)(125)} \\[1ex]
&= \frac{20}{3} \\[1ex]
&\approx 6.667
\end{align*}
The mean time to battery failure is $\frac{20}{3} \approx 6.667$ years.


**c)** In order to find $t_0$ such that $P(X>t_0)=0.99$, we solve the equation:
$$
\int_5^{t_0} \frac{2500}{x^5} dx = 0.01
$$
for $t_0$. Then doing so, 
\begin{align*}
\int_5^{t_0} \frac{2500}{x^5} dx  &= 0.01  \\[1ex]
\left[ \frac{-625}{x^4}\right]^{t_0}_{5}  &=  0.01  \\[1ex]
1 - \frac{625}{t_0^4}&= 0.01 \\[1ex]
\frac{625}{0.99} &= t_0^4 \\[1ex]
t_0 &\approx 5.012579 
\end{align*}
So, $t_0 \approx 5.01$ years, or 5 years and roughly 4 days.


# Problem 2.10
In some applications, a third parameter, called a guarantee time, is included in the models discussed in this chapter.  This parameter $G$ is the smallest time at which a failure could occur.  The survival function of the three-parameter Weibull distribution is given by
$$
S(x) = 
\begin{cases} 
1                               &\mbox{if } x < G \\ 
exp(-\lambda(x-G)^{\alpha})    &\mbox{if } x \ge G 
\end{cases}
$$
a) Find the hazard rate and the density function of the three-parameter Weibull distribution.  
b) Suppose that the survival time $X$ follows a three-parameter Weibull distribution with $\alpha=1$, $\lambda=0.0075$ and $G=100$.  Find the mean and median lifetimes.   

## Answer

**a)** Using the fact that $f(x) = -S'(x)$, we have: 
$$
f(x) = 
\begin{cases} 
0                                                              &\mbox{if } x < G \\ 
exp(-\lambda(x-G)^{\alpha})(\lambda \alpha)(x-G)^{\alpha - 1}  &\mbox{if } x \ge G 
\end{cases}
$$

And then using the fact that $h(x) = \frac{f(x)}{S(x)}$ we have:

$$
h(x) = 
\begin{cases} 
0                                  &\mbox{if } x < G \\ 
\lambda \alpha (x-G)^{\alpha - 1}  &\mbox{if } x \ge G 
\end{cases}
$$

**b)** With those values, the survival function is then
$$
S(x) = 
\begin{cases} 
1                       &\mbox{if } x < 100 \\ 
e^{(-0.0075(x-100))}    &\mbox{if } x \ge 100 
\end{cases}
$$

or rewritten 

**Mean Life** - The mean life is defined by:
$$
\mu = mrl(0) = \int_0^{\infty} S(t) dt
$$

So we have:

\begin{align*}
\mu 
&= \int_0^{\infty} S(t) dt \\[1ex]
&= 100 + \int_{100}^{\infty} S(t) dt \\[1ex]
&= 100 + \int_{100}^{\infty} e^{(-0.0075(x-100))} dt \\[1ex]
&= 100 + \int_{100}^{\infty} e^{(-0.0075(x-100))} dt \\[1ex]
&= 100 + \frac{e^{0.75}}{-0.0075} \left[ 1 / e^{0.0075 x}  \right]^{\infty}_{100} \\[1ex]
&= 100 + \frac{e^{0.75}}{-0.0075}  [0 - 1 / e^{0.75}] \\[1ex]
&= 100 + \frac{1}{0.0075} \\[1ex]
&\approx 233.3 
\end{align*}

The mean life is approximately 233.3.   

**Median Life** - Since $X$ is continuous, the median life is $x_{0.5}$ such that $S(x_{0.5})=0.5$.  The median life occurs sometime after $x=100$, and so we need to solve the equation
$$
0.5 = e^{0.75-0.0075x}
$$
Doing so
\begin{align*}
0.5 &= e^{0.75-0.0075x}  \\[1ex]
ln(0.5) &= 0.75 - 0.0075x \\[1ex]
0.0075x &= 0.75 - ln(0.5) \\[1ex]
x &= \frac{0.75 - ln(0.5)}{0.0075} \\[1ex]
x &\approx 192.42 
\end{align*}

The median life is approximately 192.42.   


# Problem 2.12
Let $X$ have a uniform distribution on the interval 0 to $\theta$ with density function
$$
f(x) = 
\begin{cases} 
1/\theta  &\mbox{for } 0 \le x \le \theta \\ 
0         &\mbox{otherwise }
\end{cases}
$$
a) Find the survival function of $X$.  
b) Find the hazard rate of $X$.   
c) Find the mean residual-life function.   

## Answer

**a)** The survival function is found by:
\begin{align*}
S(x) 
&= 1 - \int_0^x f(t) \; dt \\[1ex]
&= 1 - \int_0^x 1/\theta \; dt \\[1ex]
&= 1 - \left[ \frac{t}{\theta} \right]^x_0 \\[1ex]
&= 1 - \frac{x}{\theta}
\end{align*}
In other words, as $x$ approaches $\theta$, the survival function approaches 0.

**b)** The hazard rate function is:
\begin{align*}
h(x)
&= \frac{f(x)}{S(x)} \\[1ex]
&= \frac{1/\theta}{1 - x/\theta} \\[1ex]
&= \frac{1}{\theta - x}
\end{align*}
This makes sense, because as $x$ approaches $\theta$, the hazard approaches infinity.

**c)** And finally the mean residual life function is:
\begin{align*}
mrl(x)
&= \frac{\int_x^{\theta} 1 - t/\theta \; dt}{S(x)} \\[1ex]
&= \left[ t - \frac{t^2}{2\theta} \right]^{\theta}_x / S(x) \\[1ex]
&= \frac{(\theta - \theta / 2)-(x - x^2/(2\theta))}{1 - \frac{x}{\theta}} \\[1ex]
&= \frac{\theta/2 - x + x^2/(2\theta)}{1 - \frac{x}{\theta}} \\[1ex]
&= \frac{\theta^2 / 2 - x \theta + x^2/2}{\theta - x} \\[1ex]
&= \frac{(\theta - x)^2}{2(\theta - x)} \\[1ex]
&= \frac{\theta - x}{2} 
\end{align*}
This value also makes sense.  It is the distance between $x$ and the midpoint of $x$ and $\theta$.  In other words:
$$
\frac{x+\theta}{2} - x = \frac{\theta - x}{2}
$$

# Problem 2.15
Based on data reported to the International Bone Marrow Transplant Registry, the survival function for a person given an HLA- identical sibling transplant for refractory multiple myeloma is given by

|x                       | S(x)                 | F(x)    |
|:----------------------:|:---------------------|:--------|
|Months Post Transplant  | Survival Probability | CDF     |
|$0 \le x < 6$           | 1.00                 | 0.00    |
|$6 \le x < 12$          | 0.55                 | 0.45    |
|$12 \le x < 18$         | 0.43                 | 0.57    |
|$18 \le x < 24$         | 0.34                 | 0.66    |
|$24 \le x < 30$         | 0.30                 | 0.70    |
|$30 \le x < 36$         | 0.25                 | 0.75    | 
|$36 \le x < 42$         | 0.18                 | 0.82    |
|$42 \le x < 48$         | 0.10                 | 0.90    |
|$48 \le x < 54$         | 0.06                 | 0.94    | 
|$x \ge 54$              | 0                    | 1.00    |

a) Find the probability mass function for the time to death for a refractory multiple myeloma bone marrow transplant patient.   
b) Find the hazard rate of $X$.   
c) Find the mean residual life at 12, 24, and 36 months post transplant.   
d) Find the median residual life at 12, 24, and 36 months.   

## Answer

**a)**  The probability mass function is:
$$
p(x) = 
\begin{cases} 
0.45  &\mbox{if } x = 6 \\ 
0.12  &\mbox{if } x = 12 \\
0.09  &\mbox{if } x = 18 \\
0.04  &\mbox{if } x = 24 \\
0.05  &\mbox{if } x = 30 \\
0.07  &\mbox{if } x = 36 \\
0.08  &\mbox{if } x = 42 \\
0.04  &\mbox{if } x = 48 \\
0.06  &\mbox{if } x = 54 \\
0     &\mbox{elsewhere}
\end{cases}
$$

**b)** The hazard rate of $X$ can be found by $h(x_j) = \frac{p(x_j)}{S(x_{j-1})}$.
$$
h(x) = 
\begin{cases} 
0.45   &\mbox{if } x = 6 \\ 
0.218  &\mbox{if } x = 12 \\
0.209  &\mbox{if } x = 18 \\
0.118  &\mbox{if } x = 24 \\
0.167  &\mbox{if } x = 30 \\
0.280  &\mbox{if } x = 36 \\
0.444  &\mbox{if } x = 42 \\
0.400  &\mbox{if } x = 48 \\
1.000  &\mbox{if } x = 54 \\
0      &\mbox{elsewhere}
\end{cases}
$$

**c)** The formula for mean residual life for a discrete $X$ gives (with a simplification since each value of $x_{j+1}-x_j=6$ and each value 12, 24, and 36 are equal to an $x_j$):
$$
mrl(12) = 6 * \frac{S(12) + ..... + S(48)}{S(12)} = 6 * \frac{1.66}{0.43} \approx 23.16 \; \mbox{months }
$$

$$
mrl(24) = 6 * \frac{S(24) + ..... + S(48)}{S(24)} = 6 * \frac{0.89}{0.30} = 17.8 \;\mbox{months }
$$

$$
mrl(36) = 6 * \frac{S(36 + ..... + S(48)}{S(36)} = 6 * \frac{0.34}{0.18} \approx 11.33 \;\mbox{months }
$$


**d)** For median residual life, we are looking for the smallest value of $x$ such that $S(x) \le 0.5$.  This is equivalent to finding the smallest $x$ such that $F(x) \ge 0.5$.  The only difference is that we are conditioning on $X>x$.  For example, we are looking for the median of the distribution $X-12 | X > 12$ by finding the smallest value $x$ such that $F(x) \ge 0.5$ and where $F(x)$ is conditioned on $X>12$.  So for $mdrl(12)$ we would have:
 
|X    | X-12 = residual   | $P(X \le x|X>12)$  |
|:----|:------------------|:-------------------|
|18   |6                  |0.209               |
|24   |12                 |0.302               |
|30   |18                 |0.419               |
|36   |24                 |0.580               |
|42   |30                 |0.767               |
|48   |36                 |0.860               |
|54   |42                 |1                   |

Therefore, $mdrl(12) = 24$.  In otherwords, about have the patients who reach 12 months would survive another 24 months.  Linear interpolation between 18 and 24 months would give $6*(0.81)/1.61+18 = 21.02$ months as the median residual after reaching 12 months.  Now the next chart for $mdrl(24)$:  

|X    | X-24 = residual   | $P(X \le x|X>24)$  |
|:----|:------------------|:-------------------|
|30   |6                  |0.167               |
|36   |12                 |0.400               |
|42   |18                 |0.667               |
|48   |24                 |0.800               |
|54   |30                 |1                   |

Therefor $mdrl(24) = 18$ months.  Linear interpolation can be used to get an answer of 14.25 months.  Next, $mdrl(36)$:

|X    | X-36 = residual   | $P(X \le x|X>36)$  |
|:----|:------------------|:-------------------|
|42   |6                  |0.444               |
|48   |12                 |0.667               |
|54   |18                 |1                   |

Therefor $mdrl(36) = 12$ months.  Linear interpolation can be used to get an answer of 7.5 months.

# Problem 2.18
Given a covariate $Z$, suppose that the log survival time $Y$ follows a linear model with a logistic error distribution, that is
$$
Y = ln(X) = \mu + \beta Z + \sigma W
$$
where the pdf of $W$ is given by
$$
f(w) = \frac{e^w}{(1+e^w)^2}, \;\; -\infty < w < \infty
$$

a) For an individual with covariate Z, find the conditional survival function of the survival time $X$, given $Z$, namely, $S(x|Z)$.  
b) The odds that an individual will die prior to time $x$ is expressed by $\frac{1-S(x|Z)}{S(x|Z)}$.  Compute the odds of death prior to time $x$ for this model.     
c) Consider two individuals with different covariate values.  Show that, for any time $x$, the ratio of their odds of deaths is independent of $x$.  The log logistic regression model is the only model with this property.  


## Answer





